require("config")
-- ColorMyPencils('desert')
-- ColorMyPencils('gruvbox')
-- ColorMyPencils('tokyonight-moon')
-- vim.cmd.colorscheme("tokyonight-moon")
-- vim.cmd.colorscheme("gruvbox")
vim.cmd.colorscheme('habamax')
