return {
--     'VonHeikemen/lsp-zero.nvim',
--     branch = 'v1.x',
--     requires = {
--         {
--             'hrsh7th/nvim-cmp',
--         },
--         { 'hrsh7th/cmp-buffer' },
--         { 'hrsh7th/cmp-cmdline' },
--         { 'hrsh7th/cmp-vsnip' },
--         {
--             'hrsh7th/vim-vsnip',
--             config = function()
--                 require 'cmp'.setup {
--                     sources = {
--                         { name = 'vsnip' }
--                     }
--                 }
--             end
--         },
--         { 'hrsh7th/cmp-path' },
--         { 'hrsh7th/vim-vsnip-integ' },
--         { 'hrsh7th/cmp-path' },
--         { 'saadparwaiz1/cmp_luasnip' },
--         {
--             'hrsh7th/cmp-nvim-lsp',
--             config = function()
--                 -- local cmp = require("cmp").setup();
--                 -- local lsp = require("lsp-zero")
--                 -- local cmp_select = { behavior = cmp.SelectBehavior.Select }
--                 -- lsp.nvim_workspace()
--                 -- local cmp_mappings = lsp.defaults.cmp_mappings({
--                 --     ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
--                 --     ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
--                 --     ['<C-y>'] = cmp.mapping.confirm({ select = true }),
--                 --     ["<C-Space>"] = cmp.mapping.complete(),
--                 -- })
--                 --
--                 -- cmp_mappings['<Tab>'] = cmp.mapping.confirm({ select = true })
--                 -- cmp_mappings['<S-Tab>'] = nil
--                 --
--                 -- lsp.setup_nvim_cmp({
--                 --     mapping = cmp_mappings
--                 -- })
--                 --
--                 -- lsp.set_preferences({
--                 --     suggest_lsp_servers = false,
--                 --     sign_icons = {
--                 --         error = 'E',
--                 --         warn = 'W',
--                 --         hint = 'H',
--                 --         info = 'I'
--                 --     }
--                 -- })
--                 --
--                 -- lsp.on_attach(function(client, bufnr)
--                 --     local opts = { buffer = bufnr, remap = false }
--                 --
--                 --     vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
--                 --     vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
--                 --     vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
--                 --     vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts)
--                 --     vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
--                 --     vim.api.nvim_buf_set_keymap(bufnr, 'n', '<space>wa',
--                 --         '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>',
--                 --         opts)
--                 --     vim.api.nvim_buf_set_keymap(bufnr, 'n', '<space>wr',
--                 --         '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>',
--                 --         opts)
--                 --     vim.api.nvim_buf_set_keymap(bufnr, 'n', '<space>wl',
--                 --         '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
--                 --     vim.keymap.set("n", "<leader>vd", function() vim.diagnostic.open_float() end, opts)
--                 --     vim.keymap.set("n", "[d", function() vim.diagnostic.goto_next() end, opts)
--                 --     vim.keymap.set("n", "]d", function() vim.diagnostic.goto_prev() end, opts)
--                 --     vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action() end, opts)
--                 --     vim.keymap.set("n", "<leader>vrr", function() vim.lsp.buf.references() end, opts)
--                 --     vim.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end, opts)
--                 --     vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, opts)
--                 --     vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
--                 -- end)
--                 --
--                 -- lsp.setup()
--             end
--
--         },
--         { 'hrsh7th/cmp-nvim-lua' },
--
--         -- Snippets
--         { 'L3MON4D3/LuaSnip' },
--         { 'rafamadriz/friendly-snippets' },
--     },
--     config = function()
--     end
}
